app = "premier-call-bot"
primary_region = "nrt"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  TZ = "Asia/Tokyo"

[processes]
  app = "python bot.py"
[mounts]
  source = "data"
  destination = "/data"
